# settings-dev.yaml

name: "ginjujin"
port: 8080
logsAddress: "./logs/"

mysql:
  username: "root"
  host: "xxx.xxx.xxx.xxx"
  port: 3306
  password: "xxxxxxxxx"
  dbname: "cmdb"
  SetMaxOpenConns: 50
  SetMaxIdleConns: 100

redis:
  host: "xxx.xxx.xxx.xxx"
  port: 6379
  password: "xxxxxx"
  db: 01
jwt:
  key: "DEYsnfKMSf5XWk87VIlLASEdOp1d2ZqGksGrB"
